export const comments = [
  {
    id: 1,
    content:
      "Maecenas leo odio,https://www.w3schools.com/cssref/pr_text_text-decoration.asp ",
    created_at: "2021-08-14T13:05:26Z",
    root_id: 3,
    reply_id: "Female",
  },
  {
    id: 2,
    content: "Aliquam quis turpis eget elit ibh.",
    created_at: "2021-07-14T13:05:26Z",
    root_id: 3,
    reply_id: "Female",
  },
  {
    id: 3,
    content: "Lorem ipsum dolor sit amet, co.",
    created_at: "2020-07-14T13:05:26Z",
    root_id: null,
    reply_id: "Male",
  },
  {
    id: 4,
    content: "Suspendisse potenti. In eleifeictumst.",
    created_at: "2010-07-14T13:05:26Z",
    root_id: null,
    reply_id: "Female",
  },
  {
    id: 5,
    content: "In sagittis dui vel nisl. Duisictumst.",
    created_at: "2008-07-14T13:05:26Z",
    root_id: 1,
    reply_id: "Male",
  },
  {
    id: 6,
    content: "Maecenas leo odio, ",
    created_at: "2021-08-14T13:05:26Z",
    root_id: 3,
    reply_id: "Female",
  },
  {
    id: 7,
    content: "Aliquam quis turpis eget elit ibh.",
    created_at: "2021-07-18T13:05:26Z",
    root_id: 3,
    reply_id: "Female",
  },
  {
    id: 8,
    content: "Lorem ipsum dolor sit amet, co.",
    created_at: "2021-07-14T13:05:26Z",
    root_id: null,
    reply_id: "Male",
  },
  {
    id: 9,
    content: "Suspendisse potenti. In eleifeictumst.",
    created_at: "2022-01-14T13:05:26Z",
    root_id: null,
    reply_id: "Female",
  },
  {
    id: 10,
    content: "In sagittis dui vel nisl. Duisictumst.",
    created_at: "2003-07-14T13:05:26Z",
    root_id: 1,
    reply_id: "Male",
  },
];
